# Generated by Django 5.1.4 on 2024-12-20 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(blank=True, default='users/NoImage.png', null=True, upload_to='users'),
        ),
    ]
